### ISSUE TITLE
gams-mode is not derived from prog-mode

### ISSUE THREAD

**Issue by christophe-gouel** [ShiroTakeda/gams-mode#1]
Could you consider making gams-mode a mode derived from prog-mode? See <https://www.emacswiki.org/emacs/ProgMode#:~:text='prog%2Dmode'%20is%20a,'prog%2Dmode'%20).> for details. This would help automatically enable features that are enabled for all programming modes (for example in my case, rainbow delimiters and smart parenthesis).

If was able to program in elisp, I would propose a pull request, but I cannot do anything beyond tinkering with my init.el file.

**Comment by ShiroTakeda** [comment]
Sorry for the late reply.

I have never heard of prog-mode before, but your idea sounds good.

I will try to modify the gams-mode. Please wait a bit.

**Comment by ShiroTakeda** [comment]
I have modified gams-mode to incorporate your request. Could you try the new gams-mode?

You can download the new gams-mode from [https://github.com/ShiroTakeda/gams-mode/blob/master/gams-mode.el](https://github.com/ShiroTakeda/gams-mode/blob/master/gams-mode.el). Alternatively, you can also install it from melpa.

**Comment by christophe-gouel** [comment]
Thanks a lot Shiro.

gams-mode is now a prog-mode. 

Unfortunately, it does not solve what I expected. I wanted to be able to use the [smartparens](https://github.com/Fuco1/smartparens) package to manage the parenthesis. This does not work even though gams-mode is a prog-mode because you have changed the key bindings of "(". Even if I use 
`(gams-close-paren-always nil)`
the keybinding is still changed. I have tried to remove it by putting
`(eval-after-load "gams-mode"
  (define-key gams-mode-map "(" nil))`
in my init.el file but this does not change anything. It only works if I execute it once a gms file is launched.

Anyway, thanks for the change.

**Comment by ShiroTakeda** [comment]
Hi, Christophe

I have modified gams-mode.el so that it is compatible with smartparen-mode.

Could you please try [this developing version of gams-mode.el](https://github.com/ShiroTakeda/gams-mode/blob/9b72731b0dcea23bda97a11066bfad2aa6ca4f2a/gams-mode.el)?

To use smartparen-mode with GAMS mode, you need to add the following code in your init.el file.

    (setq gams-close-paren-always nil)
    (setq gams-close-double-quotation-always nil)
    (setq gams-close-single-quotation-always nil)
    (add-hook 'gams-mode-hook #'smartparens-mode)

**Comment by christophe-gouel** [comment]
This works perfectly.

Thanks a lot!
