### ISSUE TITLE
Faces do not seem to work inside slashes

### ISSUE THREAD

**Issue by christophe-gouel** [ShiroTakeda/gams-mode#4]
Hi,

The face inside slashes is the same as the face of the statement. See below
![image](https://user-images.githubusercontent.com/668630/173506872-f6854fdb-9238-47b2-9ca9-e3cf92e1c2c5.png)

My (limited) understanding of the code is that this should be different, but it does not seem to work. The result is the same if I switch to another theme.

Depending on the statement, it can be quite confusing. See for example:
![image](https://user-images.githubusercontent.com/668630/173507142-833cf48b-ffe2-4d36-8d73-a398d467d337.png)

**Comment by ShiroTakeda** [comment]
Certainly the color of the statement (e.g., set and model) and the color of the texts within the slash (e.g., seattle and san-diego) should be different colors.

Below is a captured image of code coloring on (uncustomized) Emacs.

![face-color](https://user-images.githubusercontent.com/3905925/174310562-59a22a64-3233-480e-846d-b55fce2aa290.png)

In my environment, different colors are used for texts of statements and texts inside slashes.

Currently, I do not know what is causing the problem.

When you execute `M-x describe-face` with the cursor over a letter, you can find out what face is used for the letter under the cursor.

Can you execute `M-x describe-face` on the word `set` and `seattle` in your code and let me know the name of the face displayed?

**Comment by christophe-gouel** [comment]
I do not manage to get the describe-face function to get to work for this.

But anyway, your comment makes me understand that the problem was coming from my configuration.

So I have checked by removing everything.

The culprit is my theme: I use the material theme and it does not seem to work well with gams-mode. I will try to find a better theme. 

Sorry for bothering you with this.

Christophe
