### ISSUE TITLE
Replace comment-region by comment-or-uncomment-region

### ISSUE THREAD

**Issue by christophe-gouel** [ShiroTakeda/gams-mode#5]
Hi,

Would it be possible to replace `comment-region` in what follows by `comment-or-uncomment-region`? This would allow the same key binding to comment and uncomment.

```{lisp}
;; `gams-comment-region' is aliased as `comment-region'.
(if (fboundp 'comment-region)
    (fset 'gams-comment-region 'comment-region)
  (fset 'gams-buffer-substring 'buffer-substring))
```

**Comment by ShiroTakeda** [comment]
I think that is a very good idea. I would like to adopt your suggestion. `C-c C-;` is binded to `gams-comment-or-uncomment-region which is an alias of `comment-or-uncomment-region`. Please try the following gams-mode.el file.

https://github.com/ShiroTakeda/gams-mode/blob/246c0bea5764e5d9d5607a1f76b4602109e66ba9/gams-mode.el

**Comment by christophe-gouel** [comment]
It works perfectly. Thanks a lot!
